<div class="wrap ekeep">
  <h1 class="headline-h1"><?php echo esc_html__('Extensions Keep', 'extensions-keep'); ?></h1>
  <div class="ekeep-export">
    <h2 class="headline-h2"><?php echo EXTENSIONS_KEEP_Icons::get_svg('file-arrow-down'); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html__('Export plugin list', 'extensions-keep'); ?></h2>
    <p><?php echo esc_html__('Clicking on "Export" will generate a list of all installed and active plugins.', 'extensions-keep'); ?><br><?php echo esc_html__('To ignore a plugin, disable it.', 'extensions-keep'); ?><br>
    <?php echo esc_html__('This list will be exported as a JSON file.', 'extensions-keep'); ?></p>
    <?php EKEEP_Admin::render_export_form(); ?>
  </div>
  <hr>
  <div class="ekeep-upload">
    <h2 class="headline-h2"><?php echo EXTENSIONS_KEEP_Icons::get_svg('file-arrow-up'); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html__('Import and install a plugin list', 'extensions-keep'); ?></h2>
    <p><?php echo esc_html__('Select a JSON file generated by Extensions Keep.', 'extensions-keep'); ?><br><?php echo esc_html__('By clicking on the "Import" button, you launch the installation of all the plugins present in the file.', 'extensions-keep'); ?><br><?php echo esc_html__('Imported plugins will be added and merged with those already installed.', 'extensions-keep'); ?></p>
    <?php EKEEP_Admin::render_upload_form(); ?>
  </div>
  <hr>
  <h2 class="headline-h2"><?php echo EXTENSIONS_KEEP_Icons::get_svg('notepad');  // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html__('Action log', 'extensions-keep'); ?></h2>
  <?php
  $this->logger->display_log();
  ?>
</div>